# config folder is under /config
# /config/configuration.yaml is a symbolic link to this file

default_config:

logger:
  default: info
  logs:
    custom_components.integration_blueprint: debug

#https://www.home-assistant.io/integrations/debugpy/
debugpy:
  # wait debugpy attach before start
  # start: true
  # wait: true
